# Generated by Django 5.0.2 on 2024-02-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_groupseat_seat_group_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ticket.status'),
        ),
    ]
