# Generated by Django 5.0.2 on 2024-02-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_status_alter_seat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.status'),
        ),
    ]
