# Generated by Django 5.0.2 on 2024-02-20 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
