# Generated by Django 5.0.2 on 2024-02-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_seat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupseat',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='group_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.groupseat'),
        ),
    ]
