# Generated by Django 5.0.2 on 2024-02-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_groupseat_price_alter_seat_group_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
