# Generated by Django 5.0.2 on 2024-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
