# Generated by Django 5.0.2 on 2024-02-11 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_seat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ticket.status'),
        ),
    ]
